apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.api.name }}
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "{{ .Values.api.env.PORT }}"
      port: {{ .Values.api.env.PORT }}
      targetPort: {{ .Values.api.env.PORT }}
  selector:
    app: {{ .Values.api.name }}
