apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.postgres.name }}
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: {{ .Values.postgres.name }}
